# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20170508_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
