# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20170522_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
